为视频序列帧提供mp4数据接口
Tencent/libpag pull request #241
Opened 2022-04-01 09:21 UTC by kataCai

2022-04-01 11:26 UTC, lvpengwei requested changes

2022-04-01 11:26 UTC, lvpengwei commented on include/pag/file.h
> +  Mp4Header = 33,
`33 ~ 44 are preserved` 这是为啥

2022-04-01 11:26 UTC, lvpengwei commented on include/pag/file.h
> +  ByteData* mp4Header;
初始值应为 `nullptr`

2022-04-01 11:26 UTC, lvpengwei commented on include/pag/file.h
> +   * get mp4 data from current video sequence
参照其他的注释格式

2022-04-01 11:26 UTC, lvpengwei commented on src/base/utils/mp4util/ExpGolomb.cpp
> +//
使用 PAG File Header

2022-04-01 11:26 UTC, lvpengwei commented on src/base/utils/mp4util/ExpGolomb.cpp
> +bool ExpGolomb::skipBytes(int size) { return skipBits(size * 8); }
需要格式化一下代码格式

2022-04-01 11:26 UTC, lvpengwei commented on src/base/utils/mp4util/ExpGolomb.cpp
> +  auto result = getBits(size, index, moveIndex);
可以直接 return

2022-04-01 11:26 UTC, lvpengwei commented on src/base/utils/mp4util/ExpGolomb.cpp
> +  for (leadingZeroCount = 0; leadingZeroCount < bitsAvailable(); ++leadingZeroCount) {
for 里面不用再初始化 `leadingZeroCount`

2022-04-01 11:26 UTC, lvpengwei commented on src/base/utils/mp4util/ExpGolomb.cpp
> +  auto prefix = skipLZ();
是否可以合并为一行？

2022-04-01 11:26 UTC, lvpengwei commented on src/base/utils/mp4util/ExpGolomb.h
> +//
ditto

2022-04-01 11:26 UTC, lvpengwei commented on src/base/utils/mp4util/ExpGolomb.h
> +#include "pag/types.h"
`#pragma once` 下面需要一个换行

2022-04-01 11:26 UTC, lvpengwei commented on src/base/utils/mp4util/ExpGolomb.cpp
> +ExpGolomb::~ExpGolomb() { data = nullptr; }
可以不要虚构函数

2022-04-01 11:26 UTC, lvpengwei commented on src/base/utils/mp4util/H264Parser.cpp
> +}
多余的虚构函数

2022-04-01 11:26 UTC, lvpengwei commented on src/base/utils/mp4util/H264Parser.cpp
> +// Created by katacai on 2022/3/8.
ditto

2022-04-01 11:26 UTC, lvpengwei commented on src/base/utils/mp4util/SimpleArray.cpp
> +}
文件结尾需要一个换行

2022-04-01 11:26 UTC, lvpengwei commented on include/pag/file.h
> +  ByteData* mp4Header;
内存泄漏，析构的时候没有 delete？

2022-04-01 13:19 UTC, kataCai commented on include/pag/file.h
> +  ByteData* mp4Header;
done

2022-04-02 02:19 UTC, kataCai commented on src/base/utils/mp4util/ExpGolomb.cpp
> +//
done

2022-04-02 02:20 UTC, kataCai commented on src/base/utils/mp4util/ExpGolomb.cpp
> +bool ExpGolomb::skipBytes(int size) { return skipBits(size * 8); }
done

2022-04-02 02:21 UTC, lvpengwei commented on include/pag/file.h
> +  Mp4Header = 33,
这个预留位置能用吗？我看后面都是在结尾增加 TAG。

2022-04-02 02:26 UTC, kataCai commented on src/base/utils/mp4util/H264Parser.cpp
> +// Created by katacai on 2022/3/8.
done

2022-04-02 02:30 UTC, kataCai commented on src/base/utils/mp4util/SimpleArray.cpp
> +}
done

2022-04-02 02:45 UTC, kataCai commented on include/pag/file.h
> +  ByteData* mp4Header;
done

2022-04-02 02:45 UTC, kataCai commented on src/base/utils/mp4util/ExpGolomb.cpp
> +ExpGolomb::~ExpGolomb() { data = nullptr; }
有个指针置null操作

2022-04-02 02:46 UTC, kataCai commented on src/base/utils/mp4util/H264Parser.cpp
> +}
有个指针需要置null, 我改下

2022-04-02 02:49 UTC, lvpengwei commented on src/base/utils/mp4util/ExpGolomb.cpp
> +ExpGolomb::~ExpGolomb() { data = nullptr; }
析构的时候不用置 nullptr

2022-04-02 02:55 UTC, kataCai commented on src/base/utils/mp4util/H264Parser.cpp
> +}
done

2022-04-02 02:55 UTC, kataCai commented on src/base/utils/mp4util/ExpGolomb.cpp
> +ExpGolomb::~ExpGolomb() { data = nullptr; }
done

2022-04-02 03:13 UTC, lvpengwei requested changes

2022-04-02 03:13 UTC, lvpengwei commented on src/base/utils/mp4util/H264Parser.h
> +#include <sstream>
不使用 `sstream`，会增加包体。

2022-04-02 03:13 UTC, lvpengwei commented on src/base/utils/mp4util/H264Parser.h
> +#include <sstream>
ditto

2022-04-02 03:13 UTC, lvpengwei commented on src/base/utils/mp4util/H264Parser.h
> +#include "base/utils/Log.h"
需要格式化，头文件引用顺序问题。

2022-04-02 03:13 UTC, lvpengwei commented on src/base/utils/mp4util/H264Parser.h
> +  int width;
int 初始化要有默认值。

2022-04-02 03:13 UTC, lvpengwei commented on src/base/utils/mp4util/H264Remuxer.cpp
> +int trackId = 0;
这个值放在全局是干啥用的？

2022-04-02 03:13 UTC, lvpengwei commented on src/base/utils/mp4util/H264Remuxer.cpp
> +Mp4Track::~Mp4Track() {}
多余的析构函数。

2022-04-02 03:13 UTC, lvpengwei commented on src/base/utils/mp4util/H264Remuxer.cpp
> +H264Remuxer::H264Remuxer() {}
多余的构造函数。

2022-04-02 03:13 UTC, lvpengwei commented on src/base/utils/mp4util/H264Remuxer.cpp
> +H264Remuxer::~H264Remuxer() { videoSequence = nullptr; }
ditto

2022-04-02 03:13 UTC, lvpengwei commented on src/base/utils/mp4util/H264Remuxer.cpp
> +  timescale = 0;
这些初始化可以直接在声明的地方。

2022-04-02 03:13 UTC, lvpengwei commented on src/base/utils/mp4util/Utils.h
> +#include <stdint.h>
可以用 `#include <cstdint>` 来替换，项目里不使用 c 的头文件引用

2022-04-02 03:13 UTC, lvpengwei commented on src/base/utils/mp4util/Utils.cpp
> +int64_t Utils::getCurrentTimeMillis() {
可以使用 `tgfx::Clock::Now()`。

2022-04-02 03:13 UTC, lvpengwei commented on src/base/utils/mp4util/SimpleArray.h
> +#pragma once
顺序问题。

2022-04-02 03:13 UTC, lvpengwei commented on src/base/utils/mp4util/SimpleArray.cpp
> +namespace pag {
`include` 下面留一个空行。

2022-04-02 03:13 UTC, lvpengwei commented on src/base/utils/mp4util/Mp4Generator.h
> +  static std::map<std::string, int> BoxSizeMap;
`BoxSizeMap` 我没搜到在哪里使用了。

2022-04-02 03:13 UTC, lvpengwei commented on src/base/utils/mp4util/Mp4Generator.h
> +#pragma once
ditto

2022-04-02 03:38 UTC, kataCai commented on include/pag/file.h
> +  Mp4Header = 33,
这个放在中间是为了放一些非必要的特性，没有这些特性，业务方也能用。  

如果放在末尾的话，有些业务方会根据TAG号限制下载，比如PAG File的TAG加到 83,  而 SDK 还是 82的，那么业务方就会提示用户升级版本了，这个是没有必要的。

2022-04-02 03:39 UTC, kataCai commented on src/base/utils/mp4util/Mp4Generator.h
> +  static std::map<std::string, int> BoxSizeMap;
<img width="882" alt="image" src="https://user-images.githubusercontent.com/3400997/161364681-75fd13b3-0e54-4e69-b708-e457a6d80182.png">

2022-04-02 06:09 UTC, kataCai commented on src/base/utils/mp4util/H264Parser.h
> +#include <sstream>
done

2022-04-02 06:10 UTC, kataCai commented on src/base/utils/mp4util/H264Parser.h
> +  int width;
done

2022-04-02 06:10 UTC, kataCai commented on src/base/utils/mp4util/H264Parser.h
> +#include "base/utils/Log.h"
done

2022-04-02 06:29 UTC, kataCai commented on src/base/utils/mp4util/Utils.cpp
> +int64_t Utils::getCurrentTimeMillis() {
done

2022-04-02 06:30 UTC, kataCai commented on src/base/utils/mp4util/SimpleArray.h
> +#pragma once
done

2022-04-02 06:30 UTC, kataCai commented on src/base/utils/mp4util/SimpleArray.cpp
> +namespace pag {
done

2022-04-02 06:31 UTC, kataCai commented on src/base/utils/mp4util/Mp4Generator.h
> +#pragma once
done

2022-04-02 08:09 UTC, kataCai commented on src/base/utils/mp4util/H264Parser.h
> +#include <sstream>
done

2022-04-02 08:09 UTC, kataCai commented on src/base/utils/mp4util/H264Remuxer.cpp
> +int trackId = 0;
这个有点问题，改成成员变量了

2022-04-02 08:11 UTC, lvpengwei commented on src/base/utils/mp4util/ExpGolomb.h
> +  ByteData* data;
变量要初始化

2022-04-02 08:16 UTC, kataCai commented on src/base/utils/mp4util/ExpGolomb.cpp
> +  for (leadingZeroCount = 0; leadingZeroCount < bitsAvailable(); ++leadingZeroCount) {
done

2022-04-02 08:16 UTC, kataCai commented on src/base/utils/mp4util/ExpGolomb.cpp
> +  auto result = getBits(size, index, moveIndex);
done

2022-04-02 08:17 UTC, kataCai commented on src/base/utils/mp4util/ExpGolomb.cpp
> +  auto prefix = skipLZ();
done

2022-04-02 08:17 UTC, kataCai commented on src/base/utils/mp4util/ExpGolomb.h
> +#include "pag/types.h"
done

2022-04-02 08:18 UTC, lvpengwei requested changes

2022-04-02 08:18 UTC, lvpengwei commented on src/base/utils/mp4util/H264Remuxer.h
> +  Mp4Flags flags;
ditto

2022-04-02 08:18 UTC, lvpengwei commented on src/base/utils/mp4util/H264Remuxer.h
> +  int id;
ditto

2022-04-02 08:18 UTC, lvpengwei commented on src/base/utils/mp4util/Mp4Generator.cpp
> +BoxParam::~BoxParam() { videoSequence = nullptr; }
ditto

2022-04-02 08:18 UTC, lvpengwei commented on src/base/utils/mp4util/Utils.cpp
> +int64_t Utils::getCurrentTimeMillis() {
这个只有一个地方在用，可以直接写在用的地方，这个文件可以删了。

2022-04-02 08:18 UTC, lvpengwei commented on src/base/utils/mp4util/Mp4Generator.cpp
> +int Mp4Generator::STSS(SimpleArray *stream, bool write) {
`SimpleArray *stream` 应为 `SimpleArray* stream`，`*` 号。格式化整个文件应该就好了

2022-04-02 08:19 UTC, kataCai commented on src/base/utils/mp4util/H264Remuxer.cpp
> +Mp4Track::~Mp4Track() {}
done

2022-04-02 08:19 UTC, kataCai commented on src/base/utils/mp4util/H264Remuxer.cpp
> +H264Remuxer::H264Remuxer() {}
done

2022-04-02 08:19 UTC, kataCai commented on src/base/utils/mp4util/H264Remuxer.cpp
> +H264Remuxer::~H264Remuxer() { videoSequence = nullptr; }
done

2022-04-02 08:26 UTC, kataCai commented on src/base/utils/mp4util/ExpGolomb.h
> +  ByteData* data;
done

2022-04-02 08:27 UTC, kataCai commented on src/base/utils/mp4util/H264Remuxer.h
> +  int id;
done

2022-04-02 08:27 UTC, kataCai commented on src/base/utils/mp4util/Mp4Generator.cpp
> +BoxParam::~BoxParam() { videoSequence = nullptr; }
done

2022-04-06 02:26 UTC, kataCai commented on src/base/utils/mp4util/Utils.cpp
> +int64_t Utils::getCurrentTimeMillis() {
done

2022-04-06 02:26 UTC, kataCai commented on src/base/utils/mp4util/Mp4Generator.cpp
> +int Mp4Generator::STSS(SimpleArray *stream, bool write) {
done

2022-04-06 03:01 UTC, lvpengwei commented on src/base/utils/mp4util/Mp4Generator.cpp
> +std::map<std::string, int> Mp4Generator::BoxSizeMap = std::map<std::string, int>();
如果没有特别的需求，建议使用`std::unordered_map`，性能更好一些。

2022-04-06 03:01 UTC, lvpengwei commented on src/base/utils/mp4util/Mp4Generator.cpp
> +    int32_t payloadSize = (int32_t)header->length() - 4;
ditto

2022-04-06 03:01 UTC, lvpengwei commented on src/base/utils/mp4util/Mp4Generator.cpp
> +    int32_t payloadSize = (int32_t)frame->fileBytes->length() - 4;
ditto

2022-04-06 03:01 UTC, lvpengwei commented on src/base/utils/mp4util/Mp4Generator.cpp
> +    LOGI("param->duration:%d", param.duration);
ditto

2022-04-06 03:03 UTC, lvpengwei commented on src/base/utils/mp4util/Mp4Generator.cpp
> +                      std::vector<WriteStreamFun>& boxFunctions, bool write) {
`const &`

2022-04-06 03:03 UTC, lvpengwei commented on src/base/utils/mp4util/Mp4Generator.h
> +  BoxParam() = default;
ditto

2022-04-06 03:05 UTC, lvpengwei commented on src/base/utils/mp4util/Mp4Generator.h
> +class BoxParam {
ditto

2022-04-06 03:06 UTC, lvpengwei commented on src/base/utils/mp4util/Mp4Generator.h
> +  void copy(const BoxParam& boxParam);
c++ 里直接用 `=` 赋值就 copy 了

2022-04-06 03:06 UTC, lvpengwei commented on src/base/utils/mp4util/SimpleArray.cpp
> +  this->capacity = capacity;
是不是可以直接在构造方法后面初始化

2022-04-06 06:14 UTC, kataCai commented on src/base/utils/mp4util/H264Parser.cpp
> +void H264Parser::SkipScalingList(ExpGolomb decoder, int count) {
改成指针传递了

2022-04-06 06:20 UTC, kataCai commented on src/base/utils/mp4util/H264Remuxer.cpp
> +  if (videoSequence->headers.size() < 2) {
是的，这里应该前移

2022-04-06 06:25 UTC, kataCai commented on src/base/utils/mp4util/H264Remuxer.cpp
> +    int64_t offset = index - pts->frame;
Frame 也是 int64_t的
<img width="482" alt="image" src="https://user-images.githubusercontent.com/3400997/161909212-d4c7fad2-870d-4045-a1ba-b4e9c4f7cd5d.png">

2022-04-06 06:42 UTC, kataCai commented on src/base/utils/mp4util/H264Remuxer.h
> +  int32_t duration = 0;
这里的duration是时间戳， 但是mp4格式存储这个只用四个字节， int64_t 还需要转换，并且有点浪费。  这里特意改成int32_t的

2022-04-06 06:48 UTC, kataCai commented on src/base/utils/mp4util/H264Remuxer.h
> +  int trackId = 0;
这里应该是private

2022-04-06 06:52 UTC, kataCai commented on src/base/utils/mp4util/Mp4Generator.cpp
> +                      std::vector<WriteStreamFun>& boxFunctions, bool write) {
改成 const 之后就没法遍历了，我改成指针吧：
<img width="704" alt="image" src="https://user-images.githubusercontent.com/3400997/161913269-3ba57c67-971e-4fec-9e10-61d41d83f52b.png">

2022-04-06 08:03 UTC, lvpengwei requested changes

2022-04-06 08:03 UTC, lvpengwei commented on src/base/utils/mp4util/Mp4Generator.cpp
> +  return tgfx::Clock::Now() * 1e-3 / 1000;
要么 `1e-6`，要么 `/ 1000000`

2022-04-06 11:26 UTC, kataCai commented on src/base/utils/mp4util/H264Remuxer.h
> +#include <algorithm>
IDE提示错了，我去掉

2022-04-06 11:41 UTC, kataCai commented on src/base/utils/mp4util/Mp4Generator.cpp
> +BoxParam Mp4Generator::param = BoxParam();
<img width="1026" alt="wecom-temp-08f41bade449aa0535553d10b05834a8" src="https://user-images.githubusercontent.com/3400997/161967011-c82f4c10-9a0d-47d2-9461-e5605b69a43c.png">
静态变量没有手动初始化的话，会编译出错

2022-04-06 12:06 UTC, lvpengwei requested changes

2022-04-06 12:06 UTC, lvpengwei commented on src/base/utils/mp4util/H264Parser.cpp
> +  std::pair<int, int> size = ReadSps(sysBytes);
获取宽高可以参照以前的计算方式

2022-04-07 02:29 UTC, lvpengwei requested changes

2022-04-07 02:29 UTC, lvpengwei commented on src/base/utils/mp4util/H264Remuxer.cpp
> +const static int SEQUENCE_NUMBER = 1;
一般是 `static const`

2022-04-07 02:29 UTC, lvpengwei commented on include/pag/file.h
> +  std::pair<int32_t, int32_t> getVideoSize();
`width`/`height`分成两个接口，返回值是`int`

2022-04-07 02:29 UTC, lvpengwei commented on src/base/utils/mp4util/H264Parser.cpp
> +SpsData H264Parser::ParseSps(ByteData* sysBytes) {
这个类感觉不需要了，只有一个地方在用，`codec` 可以在用的地方写个 `static` 的方法

2022-04-07 07:21 UTC, lvpengwei requested changes

2022-04-07 07:21 UTC, lvpengwei commented on src/base/utils/mp4util/Mp4Generator.h
> +class Mp4Generator {
这个类全部是`static`的方法和变量，是不是可以去掉`static`？

2022-04-07 09:08 UTC, kataCai commented on src/base/utils/mp4util/H264Remuxer.cpp
> +    remuxer->mp4Track.pts.emplace_back(frame->frame);
这里是存储帧数，后面会根据帧数换算成时间戳：
<img width="745" alt="image" src="https://user-images.githubusercontent.com/3400997/162163737-a371d504-3952-488c-add1-0d4bb67f9884.png">

2022-04-07 09:31 UTC, lvpengwei requested changes

2022-04-07 09:31 UTC, lvpengwei commented on src/base/utils/mp4util/Mp4Generator.h
> +  Mp4Generator(const BoxParam& param);
`explicit`

2022-04-07 09:31 UTC, lvpengwei commented on src/base/VideoSequence.cpp
> +  // The exact total width of the picture were not recorded when the video sequence frame was exported，You need to do the calculation yourself with width and alphaStartX，If an odd size is encountered
注释太长了，format 一下，应该会换行

2022-04-07 09:31 UTC, lvpengwei commented on src/base/utils/mp4util/H264Remuxer.cpp
> +  for (int i = 0; i < 3; ++i) {
`avc1.PPCCLL`

https://zhuanlan.zhihu.com/p/82266810

2022-04-07 09:31 UTC, lvpengwei commented on src/base/utils/mp4util/Mp4Generator.cpp
> +  return static_cast<int32_t>(static_cast<double>(tgfx::Clock::Now()) * 1e-6);
直接除 1000000，就不用转 `double` 了

2022-04-08 10:31 UTC, lvpengwei requested changes

2022-04-08 10:31 UTC, lvpengwei commented on src/base/utils/mp4util/H264Remuxer.h
> +  static Frame GetImplicitOffset(const std::vector<VideoFrame*>& frames);
这个不需要在头文件声明了。

2022-04-08 10:31 UTC, lvpengwei commented on src/base/utils/mp4util/Mp4BoxHelper.h
> +  static std::unique_ptr<ByteData> CreateMp4(const VideoSequence* videoSequence);
这几个应该也不需要再头文件声明

2022-04-11 09:12 UTC, lvpengwei requested changes

2022-04-11 09:12 UTC, lvpengwei commented on src/base/utils/mp4util/Mp4BoxHelper.cpp
> +static std::unique_ptr<ByteData> CreateMp4(const VideoSequence* videoSequence) {
这个方法可以不用要了

2022-04-11 09:18 UTC, lvpengwei requested changes

2022-04-11 09:22 UTC, lvpengwei requested changes

2022-04-11 09:22 UTC, lvpengwei commented on src/base/utils/mp4util/Mp4BoxHelper.cpp
> +static std::shared_ptr<Mp4Track> GenerateMp4Track(const VideoSequence* videoSequence) {
`MakeMp4Track` 好像和项目里的更适合，项目里创建对象大多是用 `Make`

2022-04-11 09:22 UTC, lvpengwei commented on src/base/utils/mp4util/Mp4BoxHelper.cpp
> +static std::unique_ptr<ByteData> GenerateMp4Data(const VideoSequence* videoSequence,
`MakeMp4Data`

2022-04-11 09:24 UTC, lvpengwei commented on src/base/utils/mp4util/Mp4Generator.h
> +  std::vector<std::shared_ptr<Mp4Sample>> samples;
这个好像可以不用智能指针

2022-04-11 11:16 UTC, kataCai commented on src/base/utils/mp4util/Mp4BoxHelper.h
> +#include "SimpleArray.h"
<img width="887" alt="image" src="https://user-images.githubusercontent.com/3400997/162728798-fe68ee78-a4d4-400c-b0b9-c1da5a210a41.png">
cpp里面需要，我挪到里面去吧

2022-04-12 08:56 UTC, lvpengwei submitted a review, later dismissed

2022-04-12 11:26 UTC, domchen commented on include/pag/file.h
> +  Mp4Header = 33,
缩写都大写： MP4Header

2022-04-12 12:45 UTC, domchen approved these changes

2022-04-13 01:09 UTC, domchen approved these changes

2022-04-13 01:10 UTC, merged