Fix video decoding failure when src is blobUrl on iOS Safari.
Tencent/libpag pull request #415
Opened 2022-07-11 07:54 UTC by zenoslin

2022-07-11 08:42 UTC, lvpengwei requested changes

2022-07-11 08:42 UTC, lvpengwei commented on src/platform/web/VideoSequenceReader.cpp
> +        if (videoFrames.size() > 0 && frame->isKeyframe) {
```suggestion
        if (!videoFrames.empty() && frame->isKeyframe) {
```

2022-07-11 08:42 UTC, lvpengwei commented on src/platform/web/VideoSequenceReader.cpp
> +        videoFrame->frame = frame->frame + sequence->frames.size();
```suggestion
        videoFrame->frame += static_cast<Frame>(sequence->frames.size());
```

2022-07-13 02:15 UTC, lvpengwei approved these changes

2022-07-13 04:33 UTC, domchen approved these changes

2022-07-13 04:33 UTC, merged