Optimize mask with feather and opacity.
Tencent/libpag pull request #526
Opened 2022-09-09 10:44 UTC by FusionXu

2022-09-13 02:15 UTC, lvpengwei requested changes

2022-09-13 02:15 UTC, lvpengwei commented on src/base/MaskData.cpp
> +  if (maskFeather != nullptr) {
直接 `delete maskFeather;` 是合法的

2022-09-13 02:15 UTC, lvpengwei commented on src/codec/tags/LayerTag.cpp
> +  if (maskFeather->value.x != 0.0f || maskFeather->value.y != 0.0f) {
这里是不是可以直接 `return`，不用再判断了

2022-09-13 02:15 UTC, lvpengwei commented on src/rendering/caches/LayerCache.h
> -
需要保留空行

2022-09-13 02:15 UTC, lvpengwei commented on src/rendering/graphics/FeatherMask.cpp
> +  if (surface == nullptr) {
`surface`在前面调用了`getCanvas`，这里是不是写错地方了

2022-09-13 02:29 UTC, FusionXu commented on src/codec/tags/LayerTag.cpp
> +  if (maskFeather->value.x != 0.0f || maskFeather->value.y != 0.0f) {
这里是需要的，如果两个值都为0的情况下，是不写入这个参数的，让maskFeather为空指针

2022-09-13 08:45 UTC, lvpengwei requested changes

2022-09-13 08:45 UTC, lvpengwei commented on src/rendering/graphics/FeatherMask.cpp
> +  bounds = MeasureFeatherMaskBounds(masks, layerFrame);
`masks`被`move`了

2022-09-13 08:45 UTC, lvpengwei commented on src/rendering/graphics/FeatherMask.cpp
> +  *rect = bounds;
`rect`可能为空吗？

2022-09-13 08:58 UTC, FusionXu commented on src/rendering/graphics/FeatherMask.cpp
> +  *rect = bounds;
> `rect`可能为空吗？

相关使用场景不会传入空指针

2022-09-13 09:03 UTC, FusionXu commented on src/rendering/graphics/FeatherMask.cpp
> +  bounds = MeasureFeatherMaskBounds(masks, layerFrame);
> `masks`被`move`了

已去除

2022-09-14 02:31 UTC, domchen approved these changes

2022-09-14 02:32 UTC, domchen approved these changes

2022-09-14 02:39 UTC, lvpengwei approved these changes

2022-09-14 05:25 UTC, closed without merging